export const MAIN_SERVICES = [
  "Cleaning",
  "Painting",
  "Handyman",
  "Plumbing",
  "Electrician",
  "Gardening",
  "Moving",
  "Carpentry",
  "Appliance Repair",
  "HVAC",
  "Pest Control",
  "Locksmith",
  "Welding",
  "CCTV Installation",
  "Solar Panels",
  "Boiler Service",
  "Roofing",
  "Flooring",
  "Tiling",
  "Plastering",
  "Window Cleaning",
  "Pressure Washing",
  "Chimney Sweep",
  "Gutter Cleaning",
  "Air Conditioning",
  "Roof Cleaning",
  "Carpet Cleaning",
  "IT Support",
];

export const SUB_SERVICES: Record<string, string[]> = {
  Cleaning: [
    "House deep clean",
    "Kitchen degrease",
    "Bathroom refresh",
    "Move-out clean",
    "Post-renovation clean",
    "Oven clean",
    "Fridge clean",
    "Window interiors",
    "Dust & vacuum",
    "Weekly maintenance",
  ],
  Painting: [
    "Single room repaint",
    "Feature wall",
    "Exterior refresh",
    "Ceiling repaint",
    "Door & trim",
    "Fence / gate",
    "Deck staining",
    "Patch & touch-up",
    "Wallpaper removal",
    "Color consultation",
  ],
  Handyman: [
    "Furniture assembly",
    "TV wall mounting",
    "Shelf / curtain fit",
    "Door / lock adjust",
    "Minor wall repair",
    "Caulking & sealant",
    "Picture hanging",
    "Flat-pack builds",
    "Baby-proofing",
    "General small jobs",
  ],
  Plumbing: [
    "Leak under sink",
    "Burst pipe",
    "Toilet not flushing",
    "Blocked drain",
    "Low water pressure",
    "Tap / mixer issue",
    "Shower not working",
    "Radiator not heating",
    "Boiler leak (plumbing)",
    "Emergency leak call-out",
  ],
  Electrician: [
    "No power in house",
    "Socket not working",
    "Light fitting install",
    "Fuse board trip",
    "Outdoor light install",
    "Smoke alarm issue",
    "Extractor fan install",
    "EV charger check",
    "Wiring check",
    "Emergency call-out",
  ],
  Gardening: [
    "Grass cut",
    "Hedge trim",
    "Garden tidy-up",
    "Weeding beds",
    "Leaf clearance",
    "Tree / bush prune",
    "Mulch / bark lay",
    "Planting help",
    "Lawn edge tidy",
    "Seasonal tidy",
  ],
  Moving: [
    "Small van move",
    "Apartment move",
    "House move",
    "Furniture move",
    "Single item move",
    "Packing help",
    "Disassemble / reassemble",
    "Stairs move help",
    "Storage drop-off",
    "Office move",
  ],
  Carpentry: [
    "Door hanging",
    "Skirting / architrave",
    "Built-in shelves",
    "Wardrobe fit",
    "Decking repair",
    "Floorboard repair",
    "Stud wall build",
    "Stair handrail",
    "Window trim",
    "Custom cabinetry",
  ],
  "Appliance Repair": [
    "Washing machine",
    "Dishwasher",
    "Fridge / freezer",
    "Oven / hob",
    "Dryer not heating",
    "Microwave issue",
    "Ice maker fault",
    "Noise / vibration",
    "Not draining",
    "Installation check",
  ],
  HVAC: [
    "No heat / cooling",
    "Filter replacement",
    "Thermostat issue",
    "Vent cleaning",
    "Duct check",
    "Fan noise",
    "No airflow",
    "Maintenance service",
    "Heat pump check",
    "Emergency call-out",
  ],
  "Pest Control": [
    "Rodent inspection",
    "Wasp nest removal",
    "Ant treatment",
    "Bed bug check",
    "Flea treatment",
    "Bird proofing",
    "Cockroach treatment",
    "Follow-up visit",
    "Entry point seal",
    "Emergency visit",
  ],
  Locksmith: [
    "Locked out",
    "Lock change",
    "New deadbolt",
    "uPVC door issue",
    "Key stuck / broken",
    "Rekey locks",
    "Window lock fix",
    "Patio door lock",
    "Handle replacement",
    "Security upgrade",
  ],
  Welding: [
    "Gate repair",
    "Balcony repair",
    "Handrail weld",
    "Fence post weld",
    "Frame reinforcement",
    "Metal fabrication",
    "On-site weld",
    "Stainless weld",
    "Aluminium weld",
    "Emergency weld",
  ],
  "CCTV Installation": [
    "New camera install",
    "Add extra camera",
    "Doorbell camera",
    "NVR/DVR setup",
    "Remote viewing setup",
    "Cable tidy",
    "Mount & aim cameras",
    "Motion alerts",
    "System health check",
    "Upgrade existing",
  ],
  "Solar Panels": [
    "New install survey",
    "Inverter issue",
    "Panel clean",
    "Output check",
    "Battery add-on",
    "Wiring tidy",
    "Monitoring setup",
    "Micro-inverter check",
    "Roof mount check",
    "System upgrade",
  ],
  "Boiler Service": [
    "Annual service",
    "Boiler not firing",
    "No hot water",
    "Pressure drop",
    "Strange noise",
    "Pilot light issue",
    "Thermostat fault",
    "Radiator cold",
    "System flush",
    "Safety check",
  ],
  Roofing: [
    "Leak investigation",
    "Missing tiles",
    "Flat roof repair",
    "Felt replacement",
    "Flashing repair",
    "Skylight leak",
    "Chimney surround",
    "Gutter join leak",
    "Storm damage",
    "Moss removal",
  ],
  Flooring: [
    "Laminate install",
    "Hardwood refinish",
    "Subfloor repair",
    "Squeaky floor fix",
    "Carpet pull-up",
    "Threshold install",
    "Skirting with floor",
    "Tile underlay prep",
    "Luxury vinyl fit",
    "Riser trim",
  ],
  Tiling: [
    "Bathroom wall tile",
    "Kitchen splashback",
    "Floor tile install",
    "Regrout & seal",
    "Cracked tile replace",
    "Shower enclosure tile",
    "Level & prep",
    "Mosaic install",
    "Outdoor tile",
    "Silicone refresh",
  ],
  Plastering: [
    "Wall skim",
    "Ceiling skim",
    "Patch repair",
    "Water damage fix",
    "Dot & dab board",
    "Artex cover",
    "Corner bead repair",
    "Float & set",
    "Small holes fix",
    "Ready-to-paint finish",
  ],
  "Window Cleaning": [
    "External windows",
    "Internal windows",
    "Frames & sills",
    "Conservatory clean",
    "Skylight clean",
    "Water-fed pole",
    "Hard-water spots",
    "Glass doors",
    "Velux clean",
    "Regular schedule",
  ],
  "Pressure Washing": [
    "Driveway clean",
    "Patio wash",
    "Deck clean",
    "Wall algae removal",
    "Fence wash",
    "Oil stain clean",
    "Garden path wash",
    "Stone clean",
    "Car park bay",
    "Pre-paint wash",
  ],
  "Chimney Sweep": [
    "Standard sweep",
    "Stove flue sweep",
    "CCTV inspection",
    "Creosote removal",
    "Bird nest removal",
    "Cap check",
    "Smoke test",
    "Draft issue check",
    "Tar build-up check",
    "Annual maintenance",
  ],
  "Gutter Cleaning": [
    "Clear gutters",
    "Downpipe unblock",
    "Check leaks",
    "Flush system",
    "Moss removal",
    "Gutter guard check",
    "Fascia clean",
    "Soffit rinse",
    "Roofline check",
    "Before winter clean",
  ],
  "Air Conditioning": [
    "No cooling",
    "Filter change",
    "Water leak",
    "Noisy unit",
    "Low airflow",
    "Thermostat fault",
    "Gas top-up check",
    "Split unit clean",
    "Odor issue",
    "Maintenance service",
  ],
  "Roof Cleaning": [
    "Moss removal",
    "Soft wash",
    "Gutter debris clear",
    "Algae treatment",
    "Roof inspection",
    "Pressure wash check",
    "Tile clean",
    "Ridge check",
    "Valley clean",
    "Post-storm tidy",
  ],
  "Carpet Cleaning": [
    "Full room clean",
    "Spot stain removal",
    "Odor treatment",
    "Pet stain clean",
    "High-traffic refresh",
    "Rug clean",
    "Stair carpet",
    "Dry time minimise",
    "Allergy clean",
    "End-of-tenancy clean",
  ],
  "IT Support": [
    "Home IT support",
    "Office IT support",
    "WiFi issues",
    "PC slow",
    "Virus removal",
    "Email setup",
    "Printer not working",
    "Smart home setup",
    "Backup & restore",
    "Network check",
    "New device setup",
    "Remote support",
  ],
};
