// FixEasy 2025 Homepage — auto-generated by Codex
// (do not edit imports or structure unless customizing later)
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

const navLinks = [
  { href: "#services", label: "Services" },
  { href: "#process", label: "How it works" },
  { href: "#platform", label: "Platform" },
  { href: "#testimonials", label: "Stories" },
  { href: "#faq", label: "FAQ" },
];

const stats = [
  { label: "Issues solved", value: "38k+" },
  { label: "Avg. response", value: "2.4h" },
  { label: "Customer rating", value: "4.9/5" },
];

const services = [
  {
    title: "Smart Diagnostics",
    description: "AI-guided intake captures photos, serials, and symptoms in seconds so your crew arrives prepared.",
    icon: "/icons/electrical.svg",
    hue: "#60a5fa",
  },
  {
    title: "Certified Pros",
    description: "Vetted technicians with verified insurance and FixEasy training for every trade in your region.",
    icon: "/icons/plumbing.svg",
    hue: "#34d399",
  },
  {
    title: "360° Coordination",
    description: "Scheduling, updates, and invoicing from one dashboard—plus real-time ETA tracking for your tenants.",
    icon: "/icons/cleaning.svg",
    hue: "#f472b6",
  },
  {
    title: "Predictive Care",
    description: "Automated maintenance playbooks and reminders extend asset life with zero spreadsheet sprawl.",
    icon: "/icons/gardening.svg",
    hue: "#facc15",
  },
  {
    title: "Portfolio Analytics",
    description: "Understand spend, MTTR, and vendor performance with executive-ready dashboards.",
    icon: "/icons/painting.svg",
    hue: "#818cf8",
  },
  {
    title: "Delightful Support",
    description: "Concierge-level support backed by 24/7 live chat keeps residents and managers in the loop.",
    icon: "/icons/moving.svg",
    hue: "#fb7185",
  },
];

const steps = [
  {
    title: "Capture",
    description:
      "Snap a video or drop a voice note—our AI extracts location, priority, and repair codes instantly.",
  },
  {
    title: "Coordinate",
    description:
      "FixEasy routes to the right pro, handles approvals, and auto-syncs updates to your property systems.",
  },
  {
    title: "Resolve",
    description:
      "Track arrival, parts, and sign-off from one glass dashboard while residents get proactive alerts.",
  },
];

const platformHighlights = [
  {
    title: "Unified command center",
    copy: "Portfolio-wide insights, service history, and vendor chat in a single modern workspace.",
  },
  {
    title: "Enterprise-grade security",
    copy: "SOC 2 compliant infrastructure, granular role controls, and full audit logs built-in.",
  },
  {
    title: "Integrations that click",
    copy: "Connect to Yardi, AppFolio, and 40+ tools with two-way sync and webhook automations.",
  },
];

const faqs = [
  {
    question: "Do you support national portfolios?",
    answer:
      "Yes. FixEasy powers multifamily, commercial, and hospitality portfolios in every major U.S. market with regional technician networks.",
  },
  {
    question: "How fast can we launch?",
    answer:
      "Most teams launch in under 10 days with guided onboarding, data migration, and live training for staff and vendors.",
  },
  {
    question: "Is FixEasy available for single properties?",
    answer:
      "We offer plans for boutique operators—start with one property and scale seamlessly as you grow.",
  },
];

const teamMembers = ["AL", "RB", "CT", "KM"];

const testimonials = [
  {
    name: "Avery Morgan",
    title: "Director of Operations, Lumen Living",
    quote:
      "FixEasy helped us shrink response times from days to hours while keeping residents in the loop. Vendors love the streamlined payouts.",
    accent: "#60a5fa",
  },
  {
    name: "Riya Patel",
    title: "Portfolio Manager, Coastline Communities",
    quote:
      "Our maintenance coordinators finally have a shared workspace that automates follow-ups and documents everything effortlessly.",
    accent: "#34d399",
  },
  {
    name: "Jordan Ellis",
    title: "Facilities Lead, Haven Hotels",
    quote:
      "Predictive alerts flag issues before guests notice. FixEasy has transformed the way we manage multi-site operations.",
    accent: "#f472b6",
  },
];

export default function HomePage() {
  return (
    <>
      <Head>
        <title>FixEasy — Property repairs, reimagined for 2025</title>
        <meta
          name="description"
          content="FixEasy unifies property maintenance with intelligent workflows, predictive scheduling, and certified pros on demand."
        />
      </Head>

      <motion.header
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="homepage__nav"
      >
        <div className="container nav__inner">
          <Link href="/" className="nav__brand">
            <span className="nav__logo">FE</span>
            <span className="nav__title">FixEasy</span>
          </Link>
          <nav className="nav__links">
            {navLinks.map((link) => (
              <Link key={link.href} href={link.href}>
                {link.label}
              </Link>
            ))}
          </nav>
          <div className="nav__actions">
            <Link href="/login" className="btn btn--ghost">
              Sign in
            </Link>
            <Link href="/demo" className="btn btn--primary">
              Book a demo
            </Link>
          </div>
        </div>
      </motion.header>

      <main className="homepage">
        <section className="hero">
          <div className="container hero__inner">
            <div className="hero__content">
              <motion.span
                className="hero__eyebrow"
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1, duration: 0.6, ease: "easeOut" }}
              >
                FIXEASY 2025 PLATFORM
              </motion.span>
              <motion.h1
                className="hero__title"
                initial={{ opacity: 0, y: 18 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2, duration: 0.7, ease: "easeOut" }}
              >
                Resolve every property issue before it becomes a headache.
              </motion.h1>
              <motion.p
                className="hero__description"
                initial={{ opacity: 0, y: 18 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3, duration: 0.7, ease: "easeOut" }}
              >
                FixEasy blends AI triage, nationwide pros, and a serene command center so your teams deliver hotel-grade experiences for every resident.
              </motion.p>
              <motion.div
                className="hero__cta"
                initial={{ opacity: 0, y: 18 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4, duration: 0.7, ease: "easeOut" }}
              >
                <Link href="/demo" className="btn btn--primary btn--lg">
                  Launch demo workspace
                </Link>
                <Link href="#platform" className="btn btn--ghost btn--lg">
                  Explore the platform
                </Link>
              </motion.div>
              <motion.div
                className="hero__stats"
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5, duration: 0.7, ease: "easeOut" }}
              >
                {stats.map((stat) => (
                  <div key={stat.label} className="hero__stat">
                    <span className="hero__stat-value">{stat.value}</span>
                    <span className="hero__stat-label">{stat.label}</span>
                  </div>
                ))}
              </motion.div>
            </div>
            <motion.div
              className="hero__visual"
              initial={{ opacity: 0, scale: 0.92 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.45, duration: 0.7, ease: "easeOut" }}
            >
              <div className="hero__visual-aurora" />
              <div className="hero__screen">
                <div className="hero__screen-header">
                  <span />
                  <span />
                  <span />
                </div>
                <div className="hero__screen-body">
                  <div className="hero__screen-pane hero__screen-pane--primary">
                    <h3>Live portfolio feed</h3>
                    <ul>
                      <li>
                        <span className="dot" />
                        Unit 340 • HVAC diagnostic complete • <strong>Resolved</strong>
                      </li>
                      <li>
                        <span className="dot" />
                        Lobby lighting • Tech on route • <strong>ETA 12:45p</strong>
                      </li>
                      <li>
                        <span className="dot" />
                        Pool pump • Predictive alert • <strong>Action in 3 days</strong>
                      </li>
                    </ul>
                  </div>
                  <div className="hero__screen-pane hero__screen-pane--secondary">
                    <h3>Team presence</h3>
                    <div className="avatar-row">
                      {teamMembers.map((initials, index) => (
                        <span key={initials} className="avatar" style={{ zIndex: 10 - index }}>
                          {initials}
                        </span>
                      ))}
                    </div>
                    <p className="hero__screen-note">Instant status sync with Slack, Teams, and email.</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        <section id="services" className="section glass-grid">
          <div className="container">
            <div className="section__header">
              <span className="section__eyebrow">Glass icon grid</span>
              <h2 className="section__title">Everything your maintenance team dreams about in one canvas.</h2>
              <p className="section__description">
                FixEasy orchestrates every step of the repair journey. Six premium modules, infinite clarity.
              </p>
            </div>
            <div className="glass-grid__layout">
              {services.map((service) => (
                <motion.article
                  key={service.title}
                  className="glass-card"
                  style={{ "--card-hue": service.hue }}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, ease: "easeOut" }}
                  viewport={{ once: true }}
                >
                  <div className="glass-card__icon">
                    <span />
                    <span />
                    <span />
                    <span />
                    <div className="glass-card__icon-inner">
                      <Image src={service.icon} alt="" width={36} height={36} />
                    </div>
                  </div>
                  <h3>{service.title}</h3>
                  <p>{service.description}</p>
                </motion.article>
              ))}
            </div>
          </div>
        </section>

        <section id="process" className="section process">
          <div className="container process__inner">
            <div className="process__intro">
              <span className="section__eyebrow">How FixEasy flows</span>
              <h2 className="section__title">From first ping to signed work order in three elegant moves.</h2>
              <p className="section__description">
                One connected workflow keeps residents, managers, and technicians aligned. No juggling apps, no lost context.
              </p>
              <Link href="/demo" className="btn btn--outline">
                See the workflow in action
              </Link>
            </div>
            <div className="process__steps">
              {steps.map((step, index) => (
                <motion.div
                  key={step.title}
                  className="process__step"
                  initial={{ opacity: 0, x: 24 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  viewport={{ once: true, amount: 0.5 }}
                >
                  <div className="process__badge">{index + 1}</div>
                  <h3>{step.title}</h3>
                  <p>{step.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        <section id="platform" className="section platform">
          <div className="container platform__inner">
            <div className="platform__visual">
              <motion.div
                className="platform__card"
                initial={{ opacity: 0, rotateX: 12, y: 24 }}
                whileInView={{ opacity: 1, rotateX: 0, y: 0 }}
                transition={{ duration: 0.8, ease: "easeOut" }}
                viewport={{ once: true }}
              >
                <div className="platform__card-header">
                  <span className="pill pill--live">LIVE</span>
                  <span className="pill">98% SLA</span>
                </div>
                <div className="platform__card-body">
                  <h3>Today&apos;s mission control</h3>
                  <ul>
                    <li>
                      <strong>12</strong> open work orders
                    </li>
                    <li>
                      <strong>4</strong> predictive alerts
                    </li>
                    <li>
                      <strong>$8.2k</strong> savings identified
                    </li>
                  </ul>
                  <div className="platform__progress">
                    <span style={{ width: "82%" }} />
                  </div>
                  <p>Automations cleared 41 repetitive tasks this week.</p>
                </div>
              </motion.div>
            </div>
            <div className="platform__content">
              <span className="section__eyebrow">Platform operating system</span>
              <h2 className="section__title">Built to empower modern property teams and their residents.</h2>
              <p className="section__description">
                Your technicians, vendors, and operators work better together with FixEasy&apos;s secure collaboration layer.
              </p>
              <div className="platform__grid">
                {platformHighlights.map((item) => (
                  <div key={item.title} className="platform__item">
                    <h3>{item.title}</h3>
                    <p>{item.copy}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="testimonials" className="section testimonials">
          <div className="container">
            <div className="section__header">
              <span className="section__eyebrow">Loved by property teams</span>
              <h2 className="section__title">“FixEasy is the quiet superpower behind our resident satisfaction scores.”</h2>
              <p className="section__description">
                Join thousands of communities delivering five-star experiences with real-time visibility, proactive insights, and responsive pros.
              </p>
            </div>
            <div className="testimonials__grid">
              {testimonials.map((testimonial) => (
                <motion.figure
                  key={testimonial.name}
                  className="testimonial-card"
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, ease: "easeOut" }}
                  viewport={{ once: true }}
                >
                  <blockquote>“{testimonial.quote}”</blockquote>
                  <figcaption>
                    <div
                      className="testimonial-card__avatar"
                      style={{ background: testimonial.accent }}
                    >
                      <span>{testimonial.name.split(" ")[0][0]}</span>
                    </div>
                    <div>
                      <strong>{testimonial.name}</strong>
                      <span>{testimonial.title}</span>
                    </div>
                  </figcaption>
                </motion.figure>
              ))}
            </div>
          </div>
        </section>

        <section id="faq" className="section faq">
          <div className="container faq__inner">
            <div className="faq__intro">
              <span className="section__eyebrow">FAQ</span>
              <h2 className="section__title">Answers for modern property operators.</h2>
              <p className="section__description">
                Can&apos;t find what you&apos;re looking for? Email concierge@fixeasy.com and our team will respond within one business day.
              </p>
            </div>
            <div className="faq__list">
              {faqs.map((item) => (
                <details key={item.question} className="faq__item">
                  <summary>{item.question}</summary>
                  <p>{item.answer}</p>
                </details>
              ))}
            </div>
          </div>
        </section>

        <section className="cta">
          <div className="container cta__inner">
            <div>
              <span className="section__eyebrow">Ready to experience the future?</span>
              <h2>Activate FixEasy across your portfolio in under 10 days.</h2>
              <p>
                Book a guided session to tailor workflows, connect integrations, and launch with a dedicated success manager.
              </p>
            </div>
            <Link href="/demo" className="btn btn--primary btn--lg">
              Schedule onboarding
            </Link>
          </div>
        </section>
      </main>

      <footer className="footer">
        <div className="container footer__inner">
          <div>
            <Link href="/" className="nav__brand">
              <span className="nav__logo">FE</span>
              <span className="nav__title">FixEasy</span>
            </Link>
            <p>Mission control for property maintenance—designed for the residents, built for the operators.</p>
          </div>
          <div className="footer__links">
            <Link href="/privacy">Privacy</Link>
            <Link href="/terms">Terms</Link>
            <Link href="mailto:hello@fixeasy.com">Contact</Link>
          </div>
        </div>
        <p className="footer__copy">© {new Date().getFullYear()} FixEasy. Crafted with care.</p>
      </footer>

      <style jsx>{`
        :global(body) {
          background:
            radial-gradient(circle at 5% -10%, rgba(79, 70, 229, 0.25), transparent 55%),
            radial-gradient(circle at 95% 10%, rgba(59, 130, 246, 0.2), transparent 60%),
            linear-gradient(180deg, #f7f9ff 0%, #f3f7ff 45%, #ecf4ff 100%);
        }

        .homepage__nav {
          position: sticky;
          top: 0;
          z-index: 100;
          backdrop-filter: blur(18px);
          background: rgba(248, 250, 255, 0.88);
          border-bottom: 1px solid rgba(148, 163, 184, 0.18);
        }

        .nav__inner {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 1.25rem;
          padding-block: 1.1rem;
        }

        .nav__brand {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          font-weight: 700;
          color: var(--text);
        }

        .nav__logo {
          display: inline-grid;
          place-items: center;
          width: 42px;
          height: 42px;
          border-radius: 12px;
          background: linear-gradient(135deg, #2563eb, #10b981);
          color: #fff;
          font-weight: 800;
          letter-spacing: -0.015em;
          box-shadow: 0 12px 32px rgba(37, 99, 235, 0.35);
        }

        .nav__title {
          font-size: 1.1rem;
          letter-spacing: -0.01em;
        }

        .nav__links {
          display: none;
          align-items: center;
          gap: 1.5rem;
          font-weight: 600;
          font-size: 0.95rem;
        }

        .nav__links a {
          color: var(--muted);
        }

        .nav__links a:hover {
          color: var(--text);
        }

        .nav__actions {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }

        .btn {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          border-radius: 999px;
          padding: 0.55rem 1.4rem;
          transition: transform var(--speed-fast) var(--ease), box-shadow var(--speed-fast) var(--ease);
          border: 1px solid transparent;
        }

        .btn--lg {
          padding: 0.75rem 1.8rem;
          font-size: 1rem;
        }

        .btn--primary {
          background: linear-gradient(135deg, #2563eb, #1d4ed8);
          color: #fff;
          box-shadow: 0 16px 40px rgba(37, 99, 235, 0.25);
        }

        .btn--primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 18px 44px rgba(37, 99, 235, 0.35);
        }

        .btn--ghost {
          background: rgba(37, 99, 235, 0.08);
          color: #1d4ed8;
        }

        .btn--ghost:hover {
          transform: translateY(-2px);
        }

        .btn--outline {
          border-color: rgba(37, 99, 235, 0.35);
          color: #1d4ed8;
          background: #fff;
        }

        .hero {
          position: relative;
          padding-block: clamp(4rem, 12vw, 8rem) clamp(4rem, 10vw, 7rem);
          overflow: hidden;
        }

        .hero::before,
        .hero::after {
          content: "";
          position: absolute;
          border-radius: 50%;
          filter: blur(0);
          opacity: 0.4;
        }

        .hero::before {
          width: 520px;
          height: 520px;
          left: -120px;
          top: -160px;
          background: radial-gradient(circle, rgba(37, 99, 235, 0.42), transparent 60%);
        }

        .hero::after {
          width: 380px;
          height: 380px;
          right: -120px;
          bottom: -60px;
          background: radial-gradient(circle, rgba(16, 185, 129, 0.4), transparent 60%);
        }

        .hero__inner {
          display: grid;
          align-items: center;
          gap: clamp(2.5rem, 6vw, 4rem);
        }

        .hero__content {
          max-width: 640px;
          position: relative;
          z-index: 1;
        }

        .hero__eyebrow {
          display: inline-flex;
          align-items: center;
          gap: 0.4rem;
          font-size: 0.75rem;
          font-weight: 700;
          letter-spacing: 0.22em;
          color: rgba(37, 99, 235, 0.9);
        }

        .hero__title {
          font-size: clamp(2.6rem, 5vw, 3.6rem);
          line-height: 1.1;
          margin-bottom: 1.25rem;
          letter-spacing: -0.02em;
        }

        .hero__description {
          font-size: clamp(1.05rem, 2vw, 1.2rem);
          color: rgba(15, 23, 42, 0.7);
          margin-bottom: 2rem;
        }

        .hero__cta {
          display: flex;
          flex-wrap: wrap;
          gap: 0.85rem;
          margin-bottom: 2.5rem;
        }

        .hero__stats {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
          gap: 1.2rem;
        }

        .hero__stat {
          padding: 1.1rem 1.2rem;
          background: rgba(255, 255, 255, 0.72);
          border: 1px solid rgba(148, 163, 184, 0.25);
          border-radius: 20px;
          backdrop-filter: blur(12px);
          box-shadow: 0 18px 40px rgba(15, 23, 42, 0.08);
        }

        .hero__stat-value {
          display: block;
          font-weight: 700;
          font-size: 1.5rem;
          color: #0f172a;
        }

        .hero__stat-label {
          color: rgba(15, 23, 42, 0.6);
          font-size: 0.9rem;
        }

        .hero__visual {
          position: relative;
          width: 100%;
          max-width: 520px;
          margin-inline: auto;
        }

        .hero__visual-aurora {
          position: absolute;
          inset: -12%;
          background:
            radial-gradient(circle at 30% 30%, rgba(59, 130, 246, 0.4), transparent 70%),
            radial-gradient(circle at 70% 60%, rgba(56, 189, 248, 0.3), transparent 70%),
            radial-gradient(circle at 50% 50%, rgba(99, 102, 241, 0.5), transparent 75%);
          filter: blur(40px);
          z-index: 0;
        }

        .hero__screen {
          position: relative;
          z-index: 1;
          border-radius: 28px;
          padding: 1.6rem;
          background: rgba(15, 23, 42, 0.78);
          border: 1px solid rgba(255, 255, 255, 0.2);
          box-shadow: 0 28px 60px rgba(15, 23, 42, 0.28);
          color: #f8fafc;
        }

        .hero__screen-header {
          display: flex;
          gap: 0.4rem;
          margin-bottom: 1.4rem;
        }

        .hero__screen-header span {
          width: 11px;
          height: 11px;
          border-radius: 50%;
          background: rgba(248, 250, 255, 0.35);
        }

        .hero__screen-body {
          display: grid;
          gap: 1.2rem;
        }

        .hero__screen-pane {
          border-radius: 18px;
          padding: 1.1rem 1.2rem;
          background: rgba(15, 23, 42, 0.45);
          border: 1px solid rgba(148, 163, 184, 0.25);
        }

        .hero__screen-pane h3 {
          margin: 0 0 0.8rem;
          font-size: 1rem;
        }

        .hero__screen-pane ul {
          list-style: none;
          margin: 0;
          padding: 0;
          display: grid;
          gap: 0.6rem;
          color: rgba(248, 250, 255, 0.86);
          font-size: 0.92rem;
        }

        .hero__screen-pane li {
          display: flex;
          gap: 0.6rem;
          align-items: center;
        }

        .dot {
          width: 10px;
          height: 10px;
          border-radius: 50%;
          background: linear-gradient(135deg, #34d399, #10b981);
          box-shadow: 0 0 0 4px rgba(52, 211, 153, 0.2);
        }

        .hero__screen-pane--secondary {
          display: grid;
          gap: 0.75rem;
        }

        .avatar-row {
          display: flex;
          align-items: center;
        }

        .avatar {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 48px;
          height: 48px;
          border-radius: 50%;
          border: 2px solid rgba(248, 250, 255, 0.8);
          margin-left: -12px;
          background: rgba(37, 99, 235, 0.4);
          color: #fff;
          font-weight: 700;
          letter-spacing: 0.04em;
        }

        .avatar:first-child {
          margin-left: 0;
        }

        .hero__screen-note {
          margin: 0;
          color: rgba(248, 250, 255, 0.7);
          font-size: 0.88rem;
        }

        .glass-grid {
          position: relative;
        }

        .glass-grid::before {
          content: "";
          position: absolute;
          inset: 10% 25% -18% 25%;
          background: radial-gradient(circle, rgba(148, 163, 184, 0.16), transparent 70%);
          z-index: -1;
          filter: blur(60px);
        }

        .glass-grid__layout {
          display: grid;
          gap: 1.8rem;
          grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
        }

        .glass-card {
          position: relative;
          padding: 2rem 1.8rem 1.7rem;
          border-radius: 26px;
          background: rgba(255, 255, 255, 0.8);
          border: 1px solid rgba(148, 163, 184, 0.18);
          box-shadow: 0 24px 60px rgba(15, 23, 42, 0.14);
          backdrop-filter: blur(18px);
          overflow: hidden;
        }

        .glass-card::after {
          content: "";
          position: absolute;
          inset: 0;
          background: linear-gradient(135deg, rgba(255, 255, 255, 0.12), transparent 65%);
          pointer-events: none;
        }

        .glass-card__icon {
          position: relative;
          width: 64px;
          height: 64px;
          border-radius: 18px;
          display: grid;
          place-items: center;
          margin-bottom: 1.4rem;
          background: rgba(255, 255, 255, 0.16);
          border: 1px solid rgba(148, 163, 184, 0.2);
        }

        .glass-card__icon span {
          position: absolute;
          border-radius: 50%;
          background: var(--card-hue, #60a5fa);
          opacity: 0.24;
        }

        .glass-card__icon span:nth-child(1) {
          width: 130%;
          height: 130%;
        }
        .glass-card__icon span:nth-child(2) {
          width: 90%;
          height: 90%;
          opacity: 0.18;
        }
        .glass-card__icon span:nth-child(3) {
          width: 50%;
          height: 50%;
          opacity: 0.32;
        }
        .glass-card__icon span:nth-child(4) {
          width: 32%;
          height: 32%;
          opacity: 0.6;
        }

        .glass-card__icon-inner {
          position: relative;
          z-index: 1;
          width: 36px;
          height: 36px;
        }

        .glass-card h3 {
          margin: 0 0 0.8rem;
          font-size: 1.2rem;
        }

        .glass-card p {
          margin: 0;
          color: rgba(15, 23, 42, 0.65);
        }

        .process__inner {
          display: grid;
          gap: 2.5rem;
          align-items: center;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        }

        .process__intro {
          display: grid;
          gap: 1.2rem;
          align-content: start;
        }

        .process__steps {
          display: grid;
          gap: 1.5rem;
        }

        .process__step {
          position: relative;
          padding: 1.6rem 1.6rem 1.6rem 1.6rem;
          border-radius: 24px;
          background: rgba(255, 255, 255, 0.82);
          border: 1px solid rgba(148, 163, 184, 0.18);
          box-shadow: 0 20px 48px rgba(15, 23, 42, 0.12);
        }

        .process__badge {
          position: absolute;
          top: -16px;
          left: 24px;
          width: 42px;
          height: 42px;
          border-radius: 16px;
          background: linear-gradient(135deg, #2563eb, #1d4ed8);
          color: #fff;
          display: inline-grid;
          place-items: center;
          font-weight: 700;
          box-shadow: 0 16px 36px rgba(37, 99, 235, 0.25);
        }

        .process__step h3 {
          margin: 1.5rem 0 0.75rem;
        }

        .process__step p {
          margin: 0;
          color: rgba(15, 23, 42, 0.65);
        }

        .platform__inner {
          display: grid;
          gap: 2.4rem;
          align-items: center;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        }

        .platform__visual {
          position: relative;
        }

        .platform__card {
          position: relative;
          padding: 2.2rem;
          border-radius: 28px;
          background: rgba(15, 23, 42, 0.9);
          border: 1px solid rgba(255, 255, 255, 0.2);
          box-shadow: 0 30px 60px rgba(15, 23, 42, 0.35);
          color: #e2e8f0;
        }

        .platform__card-header {
          display: flex;
          align-items: center;
          gap: 0.6rem;
          margin-bottom: 1.5rem;
        }

        .pill {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 0.4rem 0.75rem;
          border-radius: 999px;
          font-size: 0.7rem;
          letter-spacing: 0.12em;
          background: rgba(255, 255, 255, 0.12);
          color: #fff;
        }

        .pill--live {
          background: rgba(34, 197, 94, 0.25);
          color: #4ade80;
        }

        .platform__card-body h3 {
          margin: 0 0 1rem;
          font-size: 1.2rem;
        }

        .platform__card-body ul {
          list-style: none;
          margin: 0 0 1.4rem;
          padding: 0;
          display: grid;
          gap: 0.6rem;
        }

        .platform__card-body ul li {
          font-size: 0.95rem;
        }

        .platform__progress {
          position: relative;
          height: 6px;
          border-radius: 999px;
          background: rgba(148, 163, 184, 0.32);
          overflow: hidden;
          margin-bottom: 1rem;
        }

        .platform__progress span {
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: linear-gradient(135deg, #60a5fa, #2563eb);
        }

        .platform__content {
          display: grid;
          gap: 1.2rem;
        }

        .platform__grid {
          display: grid;
          gap: 1.1rem;
        }

        .platform__item {
          padding: 1.4rem;
          border-radius: 20px;
          background: rgba(255, 255, 255, 0.8);
          border: 1px solid rgba(148, 163, 184, 0.2);
          box-shadow: 0 18px 42px rgba(15, 23, 42, 0.12);
        }

        .platform__item h3 {
          margin: 0 0 0.5rem;
        }

        .platform__item p {
          margin: 0;
          color: rgba(15, 23, 42, 0.6);
        }

        .testimonials__grid {
          display: grid;
          gap: 1.6rem;
          grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
        }

        .testimonial-card {
          padding: 1.8rem;
          border-radius: 24px;
          background: rgba(255, 255, 255, 0.88);
          border: 1px solid rgba(148, 163, 184, 0.16);
          box-shadow: 0 20px 46px rgba(15, 23, 42, 0.12);
          display: grid;
          gap: 1.4rem;
        }

        .testimonial-card blockquote {
          margin: 0;
          font-size: 0.98rem;
          color: rgba(15, 23, 42, 0.72);
        }

        .testimonial-card__avatar {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 48px;
          height: 48px;
          border-radius: 50%;
          color: #fff;
          font-weight: 700;
          letter-spacing: 0.04em;
        }

        .testimonial-card figcaption {
          display: flex;
          align-items: center;
          gap: 0.9rem;
        }

        .testimonial-card figcaption span {
          display: block;
          color: rgba(15, 23, 42, 0.55);
          font-size: 0.85rem;
        }

        .faq__inner {
          display: grid;
          gap: 2rem;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        }

        .faq__intro {
          display: grid;
          gap: 1rem;
        }

        .faq__list {
          display: grid;
          gap: 1rem;
        }

        .faq__item {
          padding: 1.4rem 1.6rem;
          border-radius: 20px;
          background: rgba(255, 255, 255, 0.86);
          border: 1px solid rgba(148, 163, 184, 0.2);
          box-shadow: 0 20px 44px rgba(15, 23, 42, 0.12);
        }

        .faq__item summary {
          font-weight: 600;
          cursor: pointer;
          outline: none;
          list-style: none;
        }

        .faq__item summary::-webkit-details-marker {
          display: none;
        }

        .faq__item p {
          margin: 0.9rem 0 0;
          color: rgba(15, 23, 42, 0.6);
        }

        .cta {
          padding-block: clamp(3.5rem, 8vw, 5.5rem);
          background: linear-gradient(135deg, rgba(37, 99, 235, 0.9), rgba(29, 78, 216, 0.95));
          color: #f8fafc;
        }

        .cta__inner {
          display: grid;
          gap: 1.6rem;
          align-items: center;
          justify-content: space-between;
          grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
        }

        .cta h2 {
          margin: 0.6rem 0;
          font-size: clamp(1.8rem, 4vw, 2.4rem);
        }

        .cta p {
          margin: 0;
          color: rgba(248, 250, 255, 0.82);
        }

        .footer {
          padding-block: 3rem 2rem;
          background: rgba(15, 23, 42, 0.94);
          color: #cbd5f5;
        }

        .footer__inner {
          display: grid;
          gap: 2rem;
          grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
          align-items: start;
        }

        .footer p {
          margin: 0.8rem 0 0;
          color: rgba(226, 232, 240, 0.75);
        }

        .footer__links {
          display: flex;
          flex-wrap: wrap;
          gap: 1.2rem;
        }

        .footer__links a {
          color: rgba(226, 232, 240, 0.8);
        }

        .footer__links a:hover {
          color: #fff;
        }

        .footer__copy {
          text-align: center;
          color: rgba(226, 232, 240, 0.5);
          margin-top: 2rem;
          font-size: 0.85rem;
        }

        @media (min-width: 960px) {
          .nav__links {
            display: flex;
          }

          .hero__inner {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }

          .hero__screen-body {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }

          .platform__grid {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }
        }

        @media (max-width: 960px) {
          .nav__actions {
            display: none;
          }
        }

        @media (max-width: 640px) {
          .hero__title {
            font-size: 2.4rem;
          }

          .hero__stats {
            grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
          }

          .btn--lg {
            width: 100%;
          }

          .testimonial-card {
            padding: 1.6rem;
          }
        }
      `}</style>
    </>
  );
}
